### ISSUE TITLE
We need a logo for the service

### ISSUE THREAD

**Issue by grady-lad** [NomadicWeb/whereswall.ie#10]
You're on your own on this one @waddhuiy, sorry!

**Comment by decentral1se** [comment]
https://raw.githubusercontent.com/NomadicWeb/whereswall.ie/master/app/assets/images/logo.png

Working logo so far ...

**Comment by decentral1se** [comment]
We are going with this bad boy:
https://github.com/NomadicWeb/whereswall.ie/blob/master/app/assets/images/logo-plus-text2.png
